parameters:
    kachkaev_r.engine.command_line.command: /usr/bin/R
    kachkaev_r.engine.server_based.url: 127.0.0.1:8787

services:

    # face detectors
    kachkaev_r.engine.command_line:
        class: Kachkaev\RBundle\Engine\CommandLineREngine
        arguments: [%kachkaev_r.engine.command_line.command%]

    kachkaev_r.engine.server_based:
        class: Kachkaev\RBundle\Engine\ServerBasedREngine
        arguments: [%kachkaev_r.engine.server_based.url%]
        
    kachkaev_r.r:
        class: Kachkaev\RBundle\R
        arguments: [@kachkaev_r.engine.command_line]
